### ISSUE TITLE
Add support for WAR packages

### ISSUE THREAD

**Issue by CaledoniaProject** [fergarrui/custom-bytecode-analyzer#5]
Can you add support for WAR packages as well?

**Comment by fergarrui** [comment]
Hi @CaledoniaProject ,
It is done, under the /bin/ directory you can find the most recent version that supports war files (or you can build it yourself).

Thanks for reporting it!
Please let me know if you find more issues

**Comment by CaledoniaProject** [comment]
You could actually upload the `bin` folder to the `Releases` tab, which is the normal way to publish binary releases.

**Comment by fergarrui** [comment]
Yes, I didn't release anything because I consider the project in an early stage, but since I have no time to do everything I wanted to do, maybe I'll start releasing it
